export const features = [
  {
    key: 'debtors',
    title: 'Debtor Accounts',
    description: 'Manage debtor profiles, track balances, and monitor account status with AI-powered insights.',
    icon: '👤',
    color: '#3b82f6',
    endpoint: 'debtors',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'phone', label: 'Phone' },
      { key: 'total_debt', label: 'Total Debt', format: 'currency' },
      { key: 'status', label: 'Status', format: 'badge' },
      { key: 'account_number', label: 'Account #' },
    ],
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'address', label: 'Address', type: 'textarea', fullWidth: true },
      { key: 'total_debt', label: 'Total Debt ($)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'in_negotiation', 'payment_plan', 'disputed', 'delinquent', 'settled', 'closed'] },
      { key: 'account_number', label: 'Account Number', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze this debtor account and recommend the best collection strategy',
  },
  {
    key: 'campaigns',
    title: 'Collection Campaigns',
    description: 'AI-optimized outreach campaigns with performance tracking and channel optimization.',
    icon: '📢',
    color: '#8b5cf6',
    endpoint: 'campaigns',
    columns: [
      { key: 'name', label: 'Campaign' },
      { key: 'type', label: 'Type', format: 'badge' },
      { key: 'status', label: 'Status', format: 'badge' },
      { key: 'budget', label: 'Budget', format: 'currency' },
      { key: 'response_rate', label: 'Response %', format: 'percent' },
      { key: 'recovery_rate', label: 'Recovery %', format: 'percent' },
    ],
    fields: [
      { key: 'name', label: 'Campaign Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['email', 'sms', 'phone', 'mail', 'multi-channel'] },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'paused', 'completed'] },
      { key: 'target_audience', label: 'Target Audience', type: 'text' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'budget', label: 'Budget ($)', type: 'number' },
      { key: 'response_rate', label: 'Response Rate (%)', type: 'number' },
      { key: 'recovery_rate', label: 'Recovery Rate (%)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze this campaign and suggest optimizations for better recovery rates',
  },
  {
    key: 'payment-plans',
    title: 'Payment Plans',
    description: 'AI-generated payment plan proposals with debtor-friendly structures and recovery optimization.',
    icon: '💳',
    color: '#059669',
    endpoint: 'payment-plans',
    columns: [
      { key: 'debtor_name', label: 'Debtor' },
      { key: 'original_amount', label: 'Original', format: 'currency' },
      { key: 'monthly_payment', label: 'Monthly', format: 'currency' },
      { key: 'duration_months', label: 'Months' },
      { key: 'status', label: 'Status', format: 'badge' },
    ],
    fields: [
      { key: 'debtor_name', label: 'Debtor Name', type: 'text', required: true },
      { key: 'original_amount', label: 'Original Amount ($)', type: 'number' },
      { key: 'plan_amount', label: 'Plan Amount ($)', type: 'number' },
      { key: 'monthly_payment', label: 'Monthly Payment ($)', type: 'number' },
      { key: 'duration_months', label: 'Duration (months)', type: 'number' },
      { key: 'interest_rate', label: 'Interest Rate (%)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['proposed', 'negotiating', 'active', 'completed', 'defaulted', 'on_hold'] },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'next_payment_date', label: 'Next Payment', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze this payment plan and suggest optimizations for the debtor and collector',
  },
  {
    key: 'communications',
    title: 'Communication Templates',
    description: 'AI-generated empathetic, FDCPA-compliant message templates for all channels.',
    icon: '✉️',
    color: '#d97706',
    endpoint: 'communications',
    columns: [
      { key: 'template_name', label: 'Template' },
      { key: 'type', label: 'Channel', format: 'badge' },
      { key: 'tone', label: 'Tone' },
      { key: 'compliance_status', label: 'Compliance', format: 'badge' },
      { key: 'effectiveness_score', label: 'Score', format: 'percent' },
      { key: 'use_count', label: 'Uses' },
    ],
    fields: [
      { key: 'template_name', label: 'Template Name', type: 'text', required: true },
      { key: 'type', label: 'Channel', type: 'select', options: ['email', 'sms', 'phone', 'mail'] },
      { key: 'subject', label: 'Subject', type: 'text' },
      { key: 'body', label: 'Message Body', type: 'textarea', fullWidth: true },
      { key: 'tone', label: 'Tone', type: 'select', options: ['friendly', 'neutral', 'empathetic', 'professional', 'firm', 'grateful', 'helpful', 'warm', 'supportive', 'encouraging', 'celebratory'] },
      { key: 'compliance_status', label: 'Compliance', type: 'select', options: ['approved', 'pending', 'under_review', 'rejected'] },
      { key: 'effectiveness_score', label: 'Effectiveness (%)', type: 'number' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Generate an empathetic and compliant communication template for debt collection',
  },
  {
    key: 'compliance',
    title: 'Compliance Monitor',
    description: 'Track regulatory compliance across FDCPA, TCPA, FCRA, and state laws with AI auditing.',
    icon: '🛡️',
    color: '#dc2626',
    endpoint: 'compliance',
    columns: [
      { key: 'check_name', label: 'Check' },
      { key: 'regulation', label: 'Regulation' },
      { key: 'status', label: 'Status', format: 'badge' },
      { key: 'risk_level', label: 'Risk', format: 'badge' },
      { key: 'category', label: 'Category' },
    ],
    fields: [
      { key: 'check_name', label: 'Check Name', type: 'text', required: true },
      { key: 'regulation', label: 'Regulation', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pass', 'fail', 'warning', 'pending'] },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'next_review', label: 'Next Review', type: 'date' },
      { key: 'findings', label: 'Findings', type: 'textarea', fullWidth: true },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Perform a compliance analysis and identify any regulatory risks',
  },
  {
    key: 'risk',
    title: 'Risk Assessment',
    description: 'AI-powered collection probability scoring and strategy recommendations.',
    icon: '📊',
    color: '#ea580c',
    endpoint: 'risk',
    columns: [
      { key: 'debtor_name', label: 'Debtor' },
      { key: 'risk_score', label: 'Score' },
      { key: 'risk_level', label: 'Level', format: 'badge' },
      { key: 'collection_probability', label: 'Probability %', format: 'percent' },
      { key: 'estimated_recovery', label: 'Est. Recovery', format: 'currency' },
    ],
    fields: [
      { key: 'debtor_name', label: 'Debtor Name', type: 'text', required: true },
      { key: 'risk_score', label: 'Risk Score (0-100)', type: 'number' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'factors', label: 'Risk Factors', type: 'textarea', fullWidth: true },
      { key: 'recommendation', label: 'Recommendation', type: 'textarea', fullWidth: true },
      { key: 'collection_probability', label: 'Collection Probability (%)', type: 'number' },
      { key: 'estimated_recovery', label: 'Estimated Recovery ($)', type: 'number' },
      { key: 'account_age_days', label: 'Account Age (days)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Assess the risk and recommend optimal collection strategy for this debtor',
  },
  {
    key: 'analytics',
    title: 'Analytics Dashboard',
    description: 'Collection performance metrics, trends, and AI-generated optimization insights.',
    icon: '📈',
    color: '#0284c7',
    endpoint: 'analytics',
    columns: [
      { key: 'metric_name', label: 'Metric' },
      { key: 'category', label: 'Category', format: 'badge' },
      { key: 'value', label: 'Value' },
      { key: 'change_percent', label: 'Change %', format: 'change' },
      { key: 'trend', label: 'Trend', format: 'badge' },
    ],
    fields: [
      { key: 'metric_name', label: 'Metric Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['recovery', 'efficiency', 'accounts', 'settlements', 'compliance', 'performance', 'communication', 'quality'] },
      { key: 'value', label: 'Value', type: 'number' },
      { key: 'previous_value', label: 'Previous Value', type: 'number' },
      { key: 'change_percent', label: 'Change (%)', type: 'number' },
      { key: 'period', label: 'Period', type: 'select', options: ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'] },
      { key: 'period_start', label: 'Period Start', type: 'date' },
      { key: 'period_end', label: 'Period End', type: 'date' },
      { key: 'trend', label: 'Trend', type: 'select', options: ['up', 'down', 'stable'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze these collection metrics and provide optimization recommendations',
  },
  {
    key: 'disputes',
    title: 'Dispute Resolution',
    description: 'Handle debtor disputes with AI-powered analysis and compliant resolution strategies.',
    icon: '⚖️',
    color: '#7c3aed',
    endpoint: 'disputes',
    columns: [
      { key: 'debtor_name', label: 'Debtor' },
      { key: 'dispute_type', label: 'Type' },
      { key: 'status', label: 'Status', format: 'badge' },
      { key: 'amount_disputed', label: 'Amount', format: 'currency' },
      { key: 'priority', label: 'Priority', format: 'badge' },
    ],
    fields: [
      { key: 'debtor_name', label: 'Debtor Name', type: 'text', required: true },
      { key: 'dispute_type', label: 'Dispute Type', type: 'select', options: ['Amount Contested', 'Not My Debt', 'Already Paid', 'Statute of Limitations', 'Fee Dispute', 'Bankruptcy Filing', 'Payment Not Applied', 'Wrong Amount', 'Harassment Complaint', 'Settled Account'] },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'investigating', 'under_review', 'resolved', 'escalated'] },
      { key: 'amount_disputed', label: 'Amount Disputed ($)', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'resolution', label: 'Resolution', type: 'textarea', fullWidth: true },
      { key: 'filed_date', label: 'Filed Date', type: 'date' },
      { key: 'resolved_date', label: 'Resolved Date', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze this dispute and recommend a fair resolution strategy',
  },
  {
    key: 'payments',
    title: 'Payment Tracking',
    description: 'Track all payments, methods, and processing status with real-time monitoring.',
    icon: '💰',
    color: '#16a34a',
    endpoint: 'payments',
    columns: [
      { key: 'debtor_name', label: 'Debtor' },
      { key: 'amount', label: 'Amount', format: 'currency' },
      { key: 'payment_method', label: 'Method' },
      { key: 'status', label: 'Status', format: 'badge' },
      { key: 'payment_date', label: 'Date', format: 'date' },
      { key: 'reference_number', label: 'Reference' },
    ],
    fields: [
      { key: 'debtor_name', label: 'Debtor Name', type: 'text', required: true },
      { key: 'amount', label: 'Amount ($)', type: 'number' },
      { key: 'payment_method', label: 'Method', type: 'select', options: ['ACH', 'credit_card', 'check', 'wire', 'cash', 'money_order'] },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'completed', 'failed', 'declined', 'refunded'] },
      { key: 'reference_number', label: 'Reference Number', type: 'text' },
      { key: 'payment_date', label: 'Payment Date', type: 'date' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'account_number', label: 'Account Number', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze payment patterns and recommend collection optimization',
  },
  {
    key: 'agents',
    title: 'Agent Performance',
    description: 'Monitor collection agent metrics, success rates, and AI coaching recommendations.',
    icon: '👥',
    color: '#0891b2',
    endpoint: 'agents',
    columns: [
      { key: 'name', label: 'Agent' },
      { key: 'team', label: 'Team' },
      { key: 'status', label: 'Status', format: 'badge' },
      { key: 'accounts_assigned', label: 'Accounts' },
      { key: 'total_recovered', label: 'Recovered', format: 'currency' },
      { key: 'performance_score', label: 'Score', format: 'percent' },
    ],
    fields: [
      { key: 'name', label: 'Agent Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'team', label: 'Team', type: 'select', options: ['Team Alpha', 'Team Beta', 'Team Gamma'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'on_leave', 'training', 'inactive'] },
      { key: 'accounts_assigned', label: 'Accounts Assigned', type: 'number' },
      { key: 'total_recovered', label: 'Total Recovered ($)', type: 'number' },
      { key: 'success_rate', label: 'Success Rate (%)', type: 'number' },
      { key: 'performance_score', label: 'Performance Score', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze this agent performance and provide coaching recommendations',
  },
  {
    key: 'portfolios',
    title: 'Debt Portfolios',
    description: 'Manage debt portfolios with AI-powered valuation and recovery optimization.',
    icon: '📁',
    color: '#4f46e5',
    endpoint: 'portfolios',
    columns: [
      { key: 'name', label: 'Portfolio' },
      { key: 'total_accounts', label: 'Accounts' },
      { key: 'total_value', label: 'Total Value', format: 'currency' },
      { key: 'recovery_rate', label: 'Recovery %', format: 'percent' },
      { key: 'status', label: 'Status', format: 'badge' },
    ],
    fields: [
      { key: 'name', label: 'Portfolio Name', type: 'text', required: true },
      { key: 'total_accounts', label: 'Total Accounts', type: 'number' },
      { key: 'total_value', label: 'Total Value ($)', type: 'number' },
      { key: 'recovered_value', label: 'Recovered Value ($)', type: 'number' },
      { key: 'recovery_rate', label: 'Recovery Rate (%)', type: 'number' },
      { key: 'average_age_days', label: 'Avg Age (days)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['new', 'active', 'winding_down', 'closed'] },
      { key: 'acquisition_date', label: 'Acquisition Date', type: 'date' },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze this portfolio and recommend strategies to improve recovery rates',
  },
  {
    key: 'settlements',
    title: 'Settlement Offers',
    description: 'AI-calculated optimal settlement amounts with acceptance probability scoring.',
    icon: '🤝',
    color: '#be185d',
    endpoint: 'settlements',
    columns: [
      { key: 'debtor_name', label: 'Debtor' },
      { key: 'original_amount', label: 'Original', format: 'currency' },
      { key: 'settlement_amount', label: 'Settlement', format: 'currency' },
      { key: 'discount_percent', label: 'Discount %', format: 'percent' },
      { key: 'status', label: 'Status', format: 'badge' },
    ],
    fields: [
      { key: 'debtor_name', label: 'Debtor Name', type: 'text', required: true },
      { key: 'original_amount', label: 'Original Amount ($)', type: 'number' },
      { key: 'settlement_amount', label: 'Settlement Amount ($)', type: 'number' },
      { key: 'discount_percent', label: 'Discount (%)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['offered', 'negotiating', 'accepted', 'completed', 'expired', 'rejected', 'on_hold'] },
      { key: 'offered_date', label: 'Offered Date', type: 'date' },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { key: 'accepted_date', label: 'Accepted Date', type: 'date' },
      { key: 'payment_terms', label: 'Payment Terms', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Calculate the optimal settlement offer for this debtor account',
  },
  {
    key: 'schedules',
    title: 'Contact Schedules',
    description: 'AI-optimized contact timing and channel selection for maximum effectiveness.',
    icon: '📅',
    color: '#ca8a04',
    endpoint: 'schedules',
    columns: [
      { key: 'debtor_name', label: 'Debtor' },
      { key: 'contact_type', label: 'Type' },
      { key: 'scheduled_date', label: 'Date', format: 'date' },
      { key: 'status', label: 'Status', format: 'badge' },
      { key: 'priority', label: 'Priority', format: 'badge' },
      { key: 'channel', label: 'Channel', format: 'badge' },
    ],
    fields: [
      { key: 'debtor_name', label: 'Debtor Name', type: 'text', required: true },
      { key: 'contact_type', label: 'Contact Type', type: 'select', options: ['Initial Contact', 'Follow-up', 'Payment Reminder', 'Negotiation', 'Dispute Follow-up', 'Dispute Resolution', 'Escalation Call', 'Plan Check-in', 'Plan Review', 'Settlement Discussion', 'Re-engagement', 'Account Closure', 'Payment Confirmation', 'Initial Outreach'] },
      { key: 'scheduled_date', label: 'Date', type: 'date' },
      { key: 'scheduled_time', label: 'Time', type: 'time' },
      { key: 'status', label: 'Status', type: 'select', options: ['scheduled', 'completed', 'overdue', 'cancelled', 'rescheduled'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'agent_name', label: 'Agent Name', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'select', options: ['phone', 'email', 'sms', 'mail'] },
      { key: 'attempt_number', label: 'Attempt #', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Recommend the optimal contact schedule and channel for this debtor',
  },
  {
    key: 'regulatory',
    title: 'Regulatory Alerts',
    description: 'Monitor regulatory changes affecting debt collection with impact analysis.',
    icon: '📋',
    color: '#b91c1c',
    endpoint: 'regulatory',
    columns: [
      { key: 'title', label: 'Alert' },
      { key: 'regulation', label: 'Regulation' },
      { key: 'severity', label: 'Severity', format: 'badge' },
      { key: 'effective_date', label: 'Effective', format: 'date' },
      { key: 'status', label: 'Status', format: 'badge' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'regulation', label: 'Regulation', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['new_rule', 'amendment', 'court_ruling', 'guidance', 'enforcement', 'state_law', 'renewal'] },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'effective_date', label: 'Effective Date', type: 'date' },
      { key: 'impact_area', label: 'Impact Area', type: 'text' },
      { key: 'action_required', label: 'Action Required', type: 'textarea', fullWidth: true },
      { key: 'status', label: 'Status', type: 'select', options: ['action_required', 'in_progress', 'completed', 'pending', 'monitoring'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Analyze the regulatory impact and recommend compliance actions',
  },
  {
    key: 'predictions',
    title: 'Recovery Predictions',
    description: 'AI-powered recovery probability forecasting and strategy optimization.',
    icon: '🔮',
    color: '#9333ea',
    endpoint: 'predictions',
    columns: [
      { key: 'debtor_name', label: 'Debtor' },
      { key: 'debt_amount', label: 'Debt', format: 'currency' },
      { key: 'predicted_recovery', label: 'Predicted', format: 'currency' },
      { key: 'confidence_score', label: 'Confidence %', format: 'percent' },
      { key: 'prediction_model', label: 'Model' },
    ],
    fields: [
      { key: 'debtor_name', label: 'Debtor Name', type: 'text', required: true },
      { key: 'debt_amount', label: 'Debt Amount ($)', type: 'number' },
      { key: 'predicted_recovery', label: 'Predicted Recovery ($)', type: 'number' },
      { key: 'confidence_score', label: 'Confidence Score (%)', type: 'number' },
      { key: 'prediction_model', label: 'Model', type: 'select', options: ['gradient_boost', 'neural_network', 'random_forest', 'logistic_regression', 'ensemble'] },
      { key: 'factors', label: 'Key Factors', type: 'textarea', fullWidth: true },
      { key: 'time_horizon_days', label: 'Time Horizon (days)', type: 'number' },
      { key: 'recommended_strategy', label: 'Strategy', type: 'textarea', fullWidth: true },
      { key: 'predicted_date', label: 'Predicted Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    aiPrompt: 'Predict recovery probability and recommend the optimal collection strategy',
  },
];
